services:
  backend:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5241:5241"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5241
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=WebApi
      - DB_USER=postgres
      - DB_PASSWORD=123
    depends_on:
      database:
        condition: service_healthy


  frontend:
    build:
      context: ./WebApi-Vue
      dockerfile: Dockerfile
      args:
        VUE_APP_API_BASE_URL: http://localhost:5241
    ports:
      - "8080:80"

  database:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: WebApi
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  postgres-data:
